services:
  klipper:
    depends_on:
      init:
        condition: service_completed_successfully
      simulavr:
        condition: service_started
    command:
      - "-I"
      - "run/klipper.tty"
      - "-a"
      - "run/klipper.sock"
      - "/opt/cfg/generic-simulavr.cfg"

  ## simulavr
  simulavr:
    image: simulavr
    container_name: simulavr
    build:
      context: docker/klipper
      target: build-simulavr
      args: 
        VERSION: master
    volumes:
      - run:/opt/run