## Ustreamer base Service
x-ustreamer-svc: &ustreamer-svc
  image: mkuf/ustreamer:nightly
  restart: unless-stopped
  command:
    - "--host=0.0.0.0"
    - "--port=8080"
    - "--slowdown"
    - "--device=/dev/webcam"
    - "--resolution=1280x960"
    - "--format=MJPEG"
    - "--desired-fps=30"

## Add your personal config here
services:
  klipper:
    devices:
      - /dev/ttymxc3:/dev/ttymxc3

  ustreamer:
    <<: *ustreamer-svc
    container_name: ustreamer
    devices:
      - /dev/video0:/dev/webcam
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ustreamer.loadbalancer.server.port=8080"
      - "traefik.http.routers.ustreamer.rule=PathPrefix(`/stream`)"
      - "traefik.http.routers.ustreamer.entrypoints=web"