name: "image-build-common"
description: "Common runner setup to build Container Images for prind"

runs:
  using: "composite"
  steps:
    - name: "[misc] Clean Runner"
      shell: bash
      run: |
        set -x
        ## Remove files
        to_delete=(
          "/swapfile"
          "/usr/local/share/boost"
          "$AGENT_TOOLSDIRECTORY"
          "/usr/share/dotnet"
          "$ANDROID_SDK_ROOT"
          "/usr/local/lib/android"
          "$ANDROID_SDK_ROOT"
          "/usr/share/swift"
        )
        for f in ${to_delete[@]}; do
          sudo rm -rf ${f} || true
        done

        ## Clean docker
        docker system prune --all --volumes --force

    - name: "[docker] set up qemu"
      uses: docker/setup-qemu-action@v3.0.0

    - name: "[docker] set up buildx"
      uses: docker/setup-buildx-action@v3.3.0

    - name: "[prind] install requirements"
      shell: bash
      run: pip install -r scripts/build/requirements.txt
