serial:
  additionalPorts:
  - /opt/printer_data/run/klipper.tty
  autoconnect: true
  port: /opt/printer_data/run/klipper.tty
webcam:
  snapshot: http://webcam:8080/snapshot
  stream: /webcam/stream
accessControl:
  userfile: /octoprint/octoprint/users.yaml