name: 'Docs: KlipperScreen'
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/template-image-docs-workflow.yaml
      - docker/klipperscreen/README.md

jobs:
  docs:
    uses: ./.github/workflows/template-image-docs-workflow.yaml
    with:
      app: klipperscreen
      short-description: "KlipperScreen is a touchscreen GUI that interfaces with Klipper via Moonraker."
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
