name: base-image-build
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        description: 'app image to build'

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Docker Login
        uses: docker/login-action@v1.10.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Build Script
        run: bash ./scripts/build-images.sh ${{ inputs.app }} ghcr.io/${{ github.repository }}/
