name: 'Docs: Ustreamer'
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/template-image-docs-workflow.yaml
      - docker/ustreamer/README.md

jobs:
  docs:
    uses: ./.github/workflows/template-image-docs-workflow.yaml
    with:
      app: ustreamer
      short-description: "µStreamer is a lightweight and very quick server to stream MJPEG video"
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
