name: 'Docs: Klipper'
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/template-image-docs-workflow.yaml
      - docker/klipper/README.md

jobs:
  docs:
    uses: ./.github/workflows/template-image-docs-workflow.yaml
    with:
      app: klipper
      short-description: "Klipper is a 3d-Printer firmware."
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
