name: 'Build and Publish Images'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
jobs:
  build:
    strategy:
      matrix:
        app:
          - klipper
          - klipperscreen
          - moonraker
          - ustreamer
    runs-on: ubuntu-latest
    steps:
      - name: "[prind] checkout"
        uses: actions/checkout@v4
      - name: "[prind] set up build environment"
        uses: ./.github/actions/image-build-common
      - name: "[docker] login"
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "[prind] build"
        run: |
          python3 scripts/build/build.py ${{ matrix.app }} \
            --backfill 3 \
            --platform linux/amd64 \
            --platform linux/arm/v6 \
            --platform linux/arm/v7 \
            --platform linux/arm64/v8 \
            --registry docker.io/${{ secrets.DOCKERHUB_USERNAME }} \
            --push
