name: "Template: image-build-workflow"
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        description: 'app image to build'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Clean Runner
        run: |
          set -x
          ## Remove files
          to_delete=(
            "/swapfile"
            "/usr/local/share/boost"
            "$AGENT_TOOLSDIRECTORY"
            "/usr/share/dotnet"
            "$ANDROID_SDK_ROOT"
            "/usr/local/lib/android"
            "$ANDROID_SDK_ROOT"
            "/usr/share/swift"
          )
          for f in ${to_delete[@]}; do
            sudo rm -rf ${f} || true
          done

          ## Clean docker
          docker system prune --all --volumes --force

      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.2.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.7.0

      - name: Docker Login
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Build requirements
        run: pip install -r scripts/build/requirements.txt
      - name: Run Build Script
        run: |
          python3 scripts/build/build.py ${{ inputs.app }} \
            --backfill 3 \
            --platform linux/amd64 \
            --platform linux/arm/v6 \
            --platform linux/arm/v7 \
            --platform linux/arm64/v8 \
            --registry docker.io/${GITHUB_REPOSITORY_OWNER} \
            --push
