name: "Template: image-docs-workflow"
on:
  workflow_call:
    inputs:
      app:
        required: true
        type: string
        description: 'app image to build'
      short-description:
        required: true
        type: string
        description: 'Docker Hub repository short description'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  image-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Update Docker Hub Description"
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ secrets.DOCKERHUB_USERNAME }}/${{ inputs.app }}
          short-description: ${{ inputs.short-description }}
          readme-filepath: ./docker/${{ inputs.app }}/README.md
          enable-url-completion: true
